# Taps
tap 'homebrew/bundle'
tap 'jorgelbg/tap' # for pinentry-touchid

tap 'cloudfoundry/tap'
tap 'cloudfoundry/cp-core', 'https://github.tools.sap/cloudfoundry/homebrew-cp-core.git'
tap 'pivotal/tap'

# BOSH client specific
brew 'cloudfoundry/tap/bosh-cli'
brew 'cloudfoundry/tap/bbl'
brew 'cloudfoundry/tap/cf-cli'
brew 'cloudfoundry/cp-core/iacbox'
brew 'cf2go'

brew 'asdf'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'colima'
brew 'coreutils'
brew 'curl'
brew 'direnv'
brew 'docker'
brew 'docker-completion'
brew 'eza'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git'
brew 'gnu-sed'
brew 'gpg'
brew 'gpg-tui'
brew 'gpg2'
brew 'httpie'
brew 'imagemagick'
brew 'jq'
brew 'kejadlen/git-together/git-together'
brew 'lazydocker'
brew 'lazygit'
brew 'libyaml'
brew 'luarocks'
brew 'markdown-toc'
brew 'markdownlint-cli'
brew 'mas'
brew 'neovim'
brew 'oniguruma'
brew 'pinentry-touchid'
brew 'pkg-config'
brew 'prettier'
brew 'readline'
brew 'ripgrep'
brew 's3cmd'
brew 'starship'
brew 'terraform-ls'
brew 'tmux'
brew 'vault'
brew 'wget'
brew 'xplr'
brew 'xz'
brew 'yarn'
brew 'zlib'
brew 'zoxide'

cask '1password'
cask 'adguard'
cask 'capacities'
cask 'gpg-suite-no-mail'
cask 'iterm2'
cask 'keyboard-maestro'
cask 'raycast'
cask 'setapp'
cask 'slack'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'homebrew/cask-fonts/font-source-code-pro-for-powerline'
cask 'homebrew/cask-fonts/font-victor-mono-nerd-font'

# Mac App Store
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
