#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
for dir in {"${DOTBOT_DIR}","${DOTBOT_DIR}-asdf","${DOTBOT_DIR}-brew"}; do
	git -C "${dir}" submodule sync --quiet --recursive
	git submodule update --init --recursive "${dir}"
done;

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-asdf --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"
