#!/usr/bin/env bash

set -e

# Exporting the specific shell we want to work with:

SHELL='/bin/zsh'
export SHELL

# Standard dotbot pre-configuration:

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly ARGS=( "$@" )

cd "${BASEDIR}"
for dir in {"${DOTBOT_DIR}","${DOTBOT_DIR}-asdf","${DOTBOT_DIR}-brewfile"}; do
	git -C "${dir}" submodule sync --quiet --recursive
	git submodule update --init --recursive "${dir}"
done;

# Linking dotfiles:
run_dotbot () {
  local config
  config="$1"

  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASEDIR}" \
    --plugin-dir dotbot-asdf \
    --plugin-dir dotbot-brewfile \
    -c "${config}" "${ARGS[@]}"
}

run_dotbot 'steps/terminal.yml' || true
run_dotbot 'steps/dependencies_global.yml' || true
run_dotbot 'steps/dependencies_fanaka.yml' || true
#run_dotbot 'steps/dependencies_client.yml' || true
