# add homebrew to the path
test -d /opt/homebrew && eval "$(/opt/homebrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Adds `.local` binary files:
export PATH="$HOME/.local/bin:$PATH"
